"use server";
import { revalidatePath } from "next/cache";
import type { TravelExpenseRule } from "@prisma/client";
import { prisma } from "@/lib/prisma";

async function loadAccess(token:string,id:string){const access=await prisma.clientAccessToken.findUnique({where:{token}});if(!access?.active)throw new Error("この共有URLは利用できません。");const order=await prisma.workOrder.findFirst({where:{id,clientId:access.clientId},include:{staffAssignments:true}});if(!order)throw new Error("稼働依頼が見つかりません。");return order}

export async function updateClientOrder(token:string,id:string,formData:FormData){const order=await loadAccess(token,id);const actor=String(formData.get("actorName")||"").trim();if(!actor)throw new Error("担当者名を入力してください。");const plannedDays=Number(formData.get("plannedDays"));const defaultStoreName=String(formData.get("defaultStoreName")||"").trim();const rate=Number(formData.get("rateAmountExTax"));const travel=String(formData.get("travelExpense")||"") as "INCLUDED"|"SEPARATE"|"CONSULT";if(!Number.isFinite(plannedDays)||plannedDays<1||!defaultStoreName||!Number.isFinite(rate)||rate<0)throw new Error("入力内容を確認してください。");const nextStatus=order.status==="APPROVED"?"CHANGES_PENDING":order.status;await prisma.$transaction([prisma.workOrder.update({where:{id},data:{plannedDays,defaultStoreName,status:nextStatus}}),prisma.workOrderStaff.updateMany({where:{workOrderId:id},data:{rateAmountExTax:rate,travelExpense:travel}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"WORK_ORDER",entityId:id,changeType:"CLIENT_EDIT",before:{plannedDays:order.plannedDays,defaultStoreName:order.defaultStoreName,status:order.status},after:{plannedDays,defaultStoreName,rateAmountExTax:rate,travelExpense:travel,status:nextStatus},actorRole:"CLIENT",actorName:actor,reason:String(formData.get("reason")||"").trim()||null}})]);revalidatePath(`/client/${token}/requests/${id}`)}

export async function addClientDailyOverride(token:string,id:string,formData:FormData){const order=await loadAccess(token,id);const assId=String(formData.get("assignmentId")||"");const ass=order.staffAssignments.find(x=>x.id===assId);if(!ass)throw new Error("スタッフが見つかりません。");const actor=String(formData.get("actorName")||"").trim(),reason=String(formData.get("reason")||"").trim(),date=String(formData.get("workDate")||"");if(!actor||!reason||!date)throw new Error("必須項目を入力してください。");const changedStore=String(formData.get("changedStoreName")||"").trim()||null;const changedRate=Number(formData.get("changedRateExTax"));const changedTravel=(String(formData.get("changedTravelExpense")||"")||null) as TravelExpenseRule|null;const ov=await prisma.dailyWorkOverride.create({data:{workOrderStaffId:ass.id,workDate:new Date(`${date}T12:00:00+09:00`),originalStoreName:order.defaultStoreName,changedStoreName:changedStore,originalRateExTax:ass.rateAmountExTax,changedRateExTax:Number.isFinite(changedRate)&&changedRate>0?changedRate:null,originalTravelExpense:ass.travelExpense,changedTravelExpense:changedTravel,lodgingOccurred:formData.get("lodgingOccurred")==="on",otherExpenseNote:String(formData.get("otherExpenseNote")||"").trim()||null,reason,changedByRole:"CLIENT",changedByName:actor,approvalStatus:"PENDING"}});await prisma.$transaction([prisma.workOrder.update({where:{id},data:{status:"CHANGES_PENDING"}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"DAILY_OVERRIDE",entityId:ov.id,changeType:"CLIENT_DAILY_CHANGE",after:{workDate:date,changedStoreName:changedStore,changedRateExTax:Number.isFinite(changedRate)?changedRate:null,changedTravelExpense:changedTravel},actorRole:"CLIENT",actorName:actor,reason}})]);revalidatePath(`/client/${token}/requests/${id}`)}

export async function clientCancelOrder(token:string,id:string,formData:FormData){const order=await loadAccess(token,id);const actor=String(formData.get("actorName")||"").trim(),reason=String(formData.get("reason")||"").trim();if(!actor||!reason)throw new Error("担当者名と理由を入力してください。");await prisma.$transaction([prisma.workOrder.update({where:{id},data:{status:"CANCELLED",cancelledAt:new Date(),cancellationReason:reason}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"WORK_ORDER",entityId:id,changeType:"CLIENT_CANCEL",before:{status:order.status},after:{status:"CANCELLED"},actorRole:"CLIENT",actorName:actor,reason}})]);revalidatePath(`/client/${token}/requests/${id}`)}

export async function clientCancelAssignment(token:string,id:string,assignmentId:string,formData:FormData){const order=await loadAccess(token,id);const ass=order.staffAssignments.find(x=>x.id===assignmentId);if(!ass)throw new Error("スタッフが見つかりません。");const actor=String(formData.get("actorName")||"").trim(),reason=String(formData.get("reason")||"").trim();if(!actor||!reason)throw new Error("担当者名と理由を入力してください。");await prisma.$transaction([prisma.workOrderStaff.update({where:{id:assignmentId},data:{active:false,cancelledAt:new Date(),cancellationReason:reason}}),prisma.shift.updateMany({where:{workOrderStaffId:assignmentId,startTime:{gte:new Date()},cancelledAt:null},data:{cancelledAt:new Date(),cancellationReason:`取引先スタッフキャンセル: ${reason}`,cancelledBy:actor}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"WORK_ORDER_STAFF",entityId:assignmentId,changeType:"CLIENT_CANCEL_STAFF",before:{active:true},after:{active:false},actorRole:"CLIENT",actorName:actor,reason}})]);revalidatePath(`/client/${token}/requests/${id}`)}

export async function clientCancelShift(token:string,id:string,shiftId:string,formData:FormData){await loadAccess(token,id);const actor=String(formData.get("actorName")||"").trim(),reason=String(formData.get("reason")||"").trim();if(!actor||!reason)throw new Error("担当者名と理由を入力してください。");const sh=await prisma.shift.findFirst({where:{id:shiftId,workOrderStaff:{workOrderId:id}}});if(!sh)throw new Error("対象シフトが見つかりません。");await prisma.$transaction([prisma.shift.update({where:{id:shiftId},data:{cancelledAt:new Date(),cancellationReason:reason,cancelledBy:actor}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"SHIFT",entityId:shiftId,changeType:"CLIENT_CANCEL_DATE",before:{cancelledAt:sh.cancelledAt},after:{cancelledAt:new Date().toISOString()},actorRole:"CLIENT",actorName:actor,reason}})]);revalidatePath(`/client/${token}/requests/${id}`)}

export async function clientCancelSite(token:string,id:string,siteId:string,formData:FormData){await loadAccess(token,id);const actor=String(formData.get("actorName")||"").trim(),reason=String(formData.get("reason")||"").trim();if(!actor||!reason)throw new Error("担当者名と理由を入力してください。");const site=await prisma.workOrderSite.findFirst({where:{id:siteId,workOrderId:id}});if(!site)throw new Error("現場が見つかりません。");await prisma.$transaction([prisma.workOrderSite.update({where:{id:siteId},data:{cancelledAt:new Date(),cancellationReason:reason}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"SITE",entityId:siteId,changeType:"CLIENT_CANCEL_SITE",before:{cancelledAt:site.cancelledAt},after:{cancelledAt:new Date().toISOString()},actorRole:"CLIENT",actorName:actor,reason}})]);revalidatePath(`/client/${token}/requests/${id}`)}
