"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { randomBytes } from "crypto";
import type { TravelExpenseRule } from "@prisma/client";
import { requireAdmin } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
export async function approveOrder(id:string,formData:FormData){await requireAdmin();const name=String(formData.get("approverName")||"").trim();if(!name)throw new Error("承認者名は必須です");const before=await prisma.workOrder.findUnique({where:{id}});if(!before)throw new Error("依頼がありません");await prisma.$transaction([prisma.workOrder.update({where:{id},data:{status:"APPROVED",approvedAt:new Date(),approverName:name,approverPhone:String(formData.get("approverPhone")||"").trim()||null,approverEmail:String(formData.get("approverEmail")||"").trim()||null}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"WORK_ORDER",entityId:id,changeType:"APPROVE",before:{status:before.status},after:{status:"APPROVED"},actorRole:"KJ",actorName:name}})]);revalidatePath(`/admin/requests/${id}`);revalidatePath("/admin/requests")}
export async function deleteOrder(id:string){
  await requireAdmin();
  const order=await prisma.workOrder.findUnique({where:{id},include:{invoices:{select:{id:true}},staffAssignments:{select:{id:true}}}});
  if(!order) return;
  if(order.invoices.length>0) throw new Error("請求書に紐付いた案件は削除できません。誤送信ではなくキャンセルとして処理してください。");
  await prisma.workOrder.delete({where:{id}});
  revalidatePath("/admin/requests");
  redirect("/admin/requests");
}

export async function cancelOrder(id:string,formData:FormData){await requireAdmin();const actor=String(formData.get("operatorName")||"").trim();const reason=String(formData.get("reason")||"").trim();if(!actor||!reason)throw new Error("操作者名と理由は必須です");const before=await prisma.workOrder.findUnique({where:{id}});if(!before)return;await prisma.$transaction([prisma.workOrder.update({where:{id},data:{status:"CANCELLED",cancelledAt:new Date(),cancellationReason:reason}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"WORK_ORDER",entityId:id,changeType:"CANCEL",before:{status:before.status},after:{status:"CANCELLED"},actorRole:"KJ",actorName:actor,reason}})]);revalidatePath(`/admin/requests/${id}`)}
export async function terminateOrder(id:string,formData:FormData){await requireAdmin();const actor=String(formData.get("operatorName")||"").trim();const reason=String(formData.get("reason")||"").trim();const date=String(formData.get("terminatedAt")||"");if(!actor||!reason||!date)throw new Error("入力してください");const before=await prisma.workOrder.findUnique({where:{id},include:{staffAssignments:true}});if(!before)return;const terminatedAt=new Date(`${date}T00:00:00+09:00`);const assignmentIds=before.staffAssignments.map(a=>a.id);await prisma.$transaction([prisma.workOrder.update({where:{id},data:{status:"TERMINATED",terminatedAt,terminationReason:reason}}),prisma.shift.updateMany({where:{workOrderStaffId:{in:assignmentIds},startTime:{gte:terminatedAt},cancelledAt:null},data:{cancelledAt:new Date(),cancellationReason:`案件途中終了: ${reason}`,cancelledBy:actor}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"WORK_ORDER",entityId:id,changeType:"TERMINATE",before:{status:before.status},after:{status:"TERMINATED",terminatedAt:date},actorRole:"KJ",actorName:actor,reason}})]);revalidatePath(`/admin/requests/${id}`)}
export async function addSite(id:string,formData:FormData){await requireAdmin();const storeName=String(formData.get("storeName")||"").trim(),actor=String(formData.get("operatorName")||"").trim();if(!storeName||!actor)throw new Error("必須項目を入力してください");const site=await prisma.workOrderSite.create({data:{workOrderId:id,storeName,rateOverrideExTax:Number(formData.get("rateOverrideExTax"))||null,travelExpense:(String(formData.get("travelExpense")||"")||null) as TravelExpenseRule|null,notes:String(formData.get("notes")||"").trim()||null}});await prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"SITE",entityId:site.id,changeType:"ADD_SITE",after:{storeName},actorRole:"KJ",actorName:actor}});revalidatePath(`/admin/requests/${id}`)}
export async function linkShift(workOrderStaffId:string,shiftId:string,workOrderId:string){await requireAdmin();await prisma.shift.update({where:{id:shiftId},data:{workOrderStaffId}});await prisma.workOrderChangeHistory.create({data:{workOrderId,entityType:"SHIFT",entityId:shiftId,changeType:"LINK_SHIFT",after:{workOrderStaffId},actorRole:"KJ",actorName:"管理画面"}});revalidatePath(`/admin/requests/${workOrderId}`)}

export async function mapRequestedStaff(assignmentId:string,workOrderId:string,formData:FormData){await requireAdmin();const staffId=String(formData.get("staffId")||"");const operatorName=String(formData.get("operatorName")||"").trim();const reason=String(formData.get("reason")||"氏名確認・紐付け").trim();if(!staffId||!operatorName)throw new Error("スタッフと操作者名を入力してください");const current=await prisma.workOrderStaff.findUnique({where:{id:assignmentId},include:{staff:true}});if(!current)throw new Error("依頼スタッフが見つかりません");const staff=await prisma.staff.findUnique({where:{id:staffId}});if(!staff)throw new Error("スタッフが見つかりません");await prisma.$transaction([prisma.workOrderStaff.update({where:{id:assignmentId},data:{staffId,requestedName:staff.name}}),prisma.workOrderChangeHistory.create({data:{workOrderId,entityType:"WORK_ORDER_STAFF",entityId:assignmentId,changeType:"MAP_STAFF",before:{requestedName:current.requestedName,staffId:current.staffId},after:{requestedName:staff.name,staffId},actorRole:"KJ",actorName:operatorName,reason}})]);revalidatePath(`/admin/requests/${workOrderId}`)}

export async function updateRequestedStaffName(assignmentId:string,workOrderId:string,formData:FormData){await requireAdmin();const requestedName=String(formData.get("requestedName")||"").trim();const operatorName=String(formData.get("operatorName")||"").trim();if(!requestedName||!operatorName)throw new Error("稼働者名と操作者名を入力してください");const current=await prisma.workOrderStaff.findUnique({where:{id:assignmentId}});if(!current)throw new Error("依頼スタッフが見つかりません");await prisma.$transaction([prisma.workOrderStaff.update({where:{id:assignmentId},data:{staffId:null,requestedName}}),prisma.workOrderChangeHistory.create({data:{workOrderId,entityType:"WORK_ORDER_STAFF",entityId:assignmentId,changeType:"EDIT_REQUESTED_NAME",before:{requestedName:current.requestedName,staffId:current.staffId},after:{requestedName,staffId:null},actorRole:"KJ",actorName:operatorName,reason:"スタッフ一覧外の稼働者を手入力"}})]);revalidatePath(`/admin/requests/${workOrderId}`)}

export async function reviewDailyOverride(overrideId:string,workOrderId:string,decision:"APPROVED"|"REJECTED",formData:FormData){await requireAdmin();const name=String(formData.get("operatorName")||"").trim();if(!name)throw new Error("確認者名は必須です");const ov=await prisma.dailyWorkOverride.findUnique({where:{id:overrideId}});if(!ov)throw new Error("当日変更が見つかりません");await prisma.$transaction([prisma.dailyWorkOverride.update({where:{id:overrideId},data:{approvalStatus:decision,approvedAt:decision==="APPROVED"?new Date():null,approvedByName:decision==="APPROVED"?name:null}}),prisma.workOrderChangeHistory.create({data:{workOrderId,entityType:"DAILY_OVERRIDE",entityId:overrideId,changeType:decision==="APPROVED"?"APPROVE_DAILY_CHANGE":"REJECT_DAILY_CHANGE",before:{approvalStatus:ov.approvalStatus},after:{approvalStatus:decision},actorRole:"KJ",actorName:name,reason:String(formData.get("reason")||"").trim()||null}})]);revalidatePath(`/admin/requests/${workOrderId}`)}

export async function adminEditOrder(id:string,formData:FormData){await requireAdmin();const actor=String(formData.get("operatorName")||"").trim();const reason=String(formData.get("reason")||"").trim();const assignmentId=String(formData.get("assignmentId")||"");const plannedDays=Number(formData.get("plannedDays"));const defaultStoreName=String(formData.get("defaultStoreName")||"").trim();const rate=Number(formData.get("rateAmountExTax"));const absence=String(formData.get("absenceDeduction")||"") as "YES"|"NO"|"CONSULT";const travel=String(formData.get("travelExpense")||"") as "INCLUDED"|"SEPARATE"|"CONSULT";if(!actor||!assignmentId||!Number.isFinite(plannedDays)||plannedDays<1||!defaultStoreName||!Number.isFinite(rate)||rate<0)throw new Error("入力内容を確認してください");const order=await prisma.workOrder.findUnique({where:{id}});const assignment=await prisma.workOrderStaff.findUnique({where:{id:assignmentId}});if(!order||!assignment)throw new Error("対象が見つかりません");const nextStatus=order.status==="APPROVED"?"CHANGES_PENDING":order.status;await prisma.$transaction([prisma.workOrder.update({where:{id},data:{plannedDays,defaultStoreName,status:nextStatus}}),prisma.workOrderStaff.update({where:{id:assignmentId},data:{rateAmountExTax:rate,absenceDeduction:absence,travelExpense:travel}}),prisma.workOrderChangeHistory.create({data:{workOrderId:id,entityType:"WORK_ORDER_STAFF",entityId:assignmentId,changeType:"KJ_EDIT",before:{plannedDays:order.plannedDays,defaultStoreName:order.defaultStoreName,rateAmountExTax:assignment.rateAmountExTax,absenceDeduction:assignment.absenceDeduction,travelExpense:assignment.travelExpense,status:order.status},after:{plannedDays,defaultStoreName,rateAmountExTax:rate,absenceDeduction:absence,travelExpense:travel,status:nextStatus},actorRole:"KJ",actorName:actor,reason:reason||null}})]);revalidatePath(`/admin/requests/${id}`)}

export async function cancelAssignment(assignmentId:string,workOrderId:string,formData:FormData){await requireAdmin();const actor=String(formData.get("operatorName")||"").trim();const reason=String(formData.get("reason")||"").trim();if(!actor||!reason)throw new Error("操作者名と理由は必須です");const ass=await prisma.workOrderStaff.findUnique({where:{id:assignmentId}});if(!ass)return;await prisma.$transaction([prisma.workOrderStaff.update({where:{id:assignmentId},data:{active:false,cancelledAt:new Date(),cancellationReason:reason}}),prisma.shift.updateMany({where:{workOrderStaffId:assignmentId,startTime:{gte:new Date()},cancelledAt:null},data:{cancelledAt:new Date(),cancellationReason:`スタッフ稼働キャンセル: ${reason}`,cancelledBy:actor}}),prisma.workOrderChangeHistory.create({data:{workOrderId,entityType:"WORK_ORDER_STAFF",entityId:assignmentId,changeType:"CANCEL_STAFF",before:{active:ass.active},after:{active:false},actorRole:"KJ",actorName:actor,reason}})]);revalidatePath(`/admin/requests/${workOrderId}`)}

export async function cancelLinkedShift(shiftId:string,workOrderId:string,formData:FormData){await requireAdmin();const actor=String(formData.get("operatorName")||"").trim();const reason=String(formData.get("reason")||"").trim();if(!actor||!reason)throw new Error("操作者名と理由は必須です");const sh=await prisma.shift.findUnique({where:{id:shiftId}});if(!sh)return;await prisma.$transaction([prisma.shift.update({where:{id:shiftId},data:{cancelledAt:new Date(),cancellationReason:reason,cancelledBy:actor}}),prisma.workOrderChangeHistory.create({data:{workOrderId,entityType:"SHIFT",entityId:shiftId,changeType:"CANCEL_DATE",before:{cancelledAt:sh.cancelledAt},after:{cancelledAt:new Date().toISOString()},actorRole:"KJ",actorName:actor,reason}})]);revalidatePath(`/admin/requests/${workOrderId}`)}

export async function issueWorkOrderShare(workOrderId:string){await requireAdmin();await prisma.workOrderAccessToken.updateMany({where:{workOrderId,active:true},data:{active:false,revokedAt:new Date()}});const token=randomBytes(24).toString("hex");await prisma.workOrderAccessToken.create({data:{workOrderId,token}});revalidatePath(`/admin/requests/${workOrderId}`)}

export async function stopWorkOrderShare(workOrderId:string){await requireAdmin();await prisma.workOrderAccessToken.updateMany({where:{workOrderId,active:true},data:{active:false,revokedAt:new Date()}});revalidatePath(`/admin/requests/${workOrderId}`)}
